apiVersion: v1
kind: Service
metadata:
  name: app-elasticsearch-service
spec:
  type: LoadBalancer
  ports:
  - port: 9200
  selector:
    app: app-elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-elasticsearch-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-elasticsearch
  template:
    metadata:
      labels:
        app: app-elasticsearch
    spec:
      containers:
      - name: search
        image: elasticsearch:2
        ports:
        - containerPort: 9200